language: java

jdk:
  - openjdk17

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - cd ./core
  - chmod +x ./gradlew

before_script: "./gradlew version-up"

script: "./gradlew clean build"

before_deploy:
  - ls -a
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy ./*
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/core.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: cf-archive-s3-bucket
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait_until_deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: cf-archive-s3-bucket
    key: core.zip
    bundle_type: zip
    application: cf-code-deploy
    deployment_group: cf-service-group
    region: ap-northeast-2
    wait-until-deployed: true

notifications:
  email:
    recipients:
      - althea_@naver.com
